import http from 'k6/http';
import { check } from 'k6';
import { Rate } from 'k6/metrics';

// All three priority tiers under load at once. premiere.js and reads.js each exercise one path in
// isolation, which can never show shedding *choosing* between them — this one offers far more
// traffic than AdmissionControl will admit and records which tier absorbs the loss.
//
// Offered load vs capacity (AdmissionControl sizing: 8000 / 1500 / 500 = 10,000/s):
//
//   tier            offered   bucket   expected
//   PLAYBACK_WRITE    7,000     8,000   admitted in full
//   RESUME_READ       3,000     1,500   partly shed (2x its bucket)
//   BROWSE_READ       1,000       500   partly shed (2x its bucket)
//   total            11,000    10,000   modest overload
//
// Writes are offered *below* their bucket on purpose. That is the whole claim: the write tier is
// sized for the write volume a premiere actually produces, and the excess read traffic is what the
// system gives up. A run where every tier is over its bucket proves only that buckets work.
//
// Read peaks were 9,000/4,000 originally (6x/8x their buckets, 20,000/s total). That run showed
// real shedding working correctly, but total offered load — generated by k6 and served by the app,
// both on this one machine, alongside Kafka/Postgres/Redis in Docker — pushed CPU contention high
// enough that Redis calls started missing their 50ms budget from slowness alone (not an outage),
// and the OS itself refused some connections outright. Lowered to keep each read tier meaningfully
// over its own bucket (still proves shedding) without over-subscribing the machine generating and
// serving the load at the same time.
const WRITE_PEAK = Number(__ENV.WRITE_PEAK || 7000);
const RESUME_PEAK = Number(__ENV.RESUME_PEAK || 3000);
const BROWSE_PEAK = Number(__ENV.BROWSE_PEAK || 1000);

// Per tier, so the gate is readable straight off the summary rather than inferred from a blended
// http_req_failed — which counts our own deliberate 429s as failures and would hide the result.
const writeSuccess = new Rate('write_success');
const resumeShed = new Rate('resume_shed');
const browseShed = new Rate('browse_shed');

// The tentpole curve from premiere.js, identical shape so the runs are comparable.
const stages = (target) => [
  { duration: '15s', target: Math.round(target / 40) },
  { duration: '60s', target: target },
  { duration: '30s', target: target },
];

export const options = {
  scenarios: {
    playback_writes: {
      executor: 'ramping-arrival-rate',
      exec: 'playbackWrite',
      startRate: 50,
      timeUnit: '1s',
      preAllocatedVUs: 800,
      maxVUs: 6000,
      stages: stages(WRITE_PEAK),
    },
    resume_reads: {
      executor: 'ramping-arrival-rate',
      exec: 'resumeRead',
      startRate: 50,
      timeUnit: '1s',
      preAllocatedVUs: 800,
      maxVUs: 6000,
      stages: stages(RESUME_PEAK),
    },
    browse_reads: {
      executor: 'ramping-arrival-rate',
      exec: 'browseRead',
      startRate: 25,
      timeUnit: '1s',
      preAllocatedVUs: 400,
      maxVUs: 3000,
      stages: stages(BROWSE_PEAK),
    },
  },
  thresholds: {
    // The phase-2 gate item, asserted by the tool rather than eyeballed.
    write_success: ['rate>0.99'],
  },
};

const PROFILES = Array.from({ length: 500 }, (_, i) => `p-${i}`);
const TITLES = Array.from({ length: 50 }, (_, i) => `t-${i}`);
const pick = (a) => a[Math.floor(Math.random() * a.length)];

export function playbackWrite() {
  const body = JSON.stringify({
    profileId: pick(PROFILES),
    titleId: pick(TITLES),
    deviceId: 'dev-1',
    positionSeconds: Math.floor(Math.random() * 3600),
    durationSeconds: 3600,
    clientTimestamp: Date.now(),
    sequence: Date.now(),
  });

  const res = http.post('http://localhost:8080/v1/playback/heartbeat', body, {
    headers: { 'Content-Type': 'application/json' },
  });

  writeSuccess.add(res.status === 202);
  check(res, {
    'write 202': (r) => r.status === 202,
    'write 429 (shed)': (r) => r.status === 429,
    'write other (real error)': (r) => r.status !== 202 && r.status !== 429,
  });
}

export function resumeRead() {
  const res = http.get(
    `http://localhost:8080/v1/playback/resume/${pick(TITLES)}`,
    { headers: { 'X-Profile-Id': pick(PROFILES) } },
  );

  resumeShed.add(res.status === 429);
  check(res, {
    'resume 200/404 (served)': (r) => r.status === 200 || r.status === 404,
    'resume 429 (shed)': (r) => r.status === 429,
    'resume other (real error)': (r) => r.status !== 200 && r.status !== 404 && r.status !== 429,
  });
}

export function browseRead() {
  const res = http.get('http://localhost:8080/v1/playback/continue-watching', {
    headers: { 'X-Profile-Id': pick(PROFILES) },
  });

  browseShed.add(res.status === 429);
  check(res, {
    'browse 200 (served)': (r) => r.status === 200,
    'browse 429 (shed)': (r) => r.status === 429,
    'browse other (real error)': (r) => r.status !== 200 && r.status !== 429,
  });
}
